# Generated by Django 3.1.1 on 2020-11-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILES_DB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='passed',
            new_name='Info',
        ),
        migrations.AddField(
            model_name='profiles',
            name='Passed',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
