# Generated by Django 3.1.1 on 2020-10-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSON1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=32)),
                ('img_url', models.TextField(max_length=256)),
                ('klass', models.TextField(max_length=256)),
                ('number', models.TextField(max_length=256)),
                ('text', models.TextField(max_length=256)),
                ('title', models.TextField(max_length=256)),
            ],
        ),
    ]
