# Generated by Django 3.1.1 on 2020-11-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUIZES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizer',
            name='descQuiz',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
