# Generated by Django 3.1.1 on 2020-11-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QUIZES', '0002_quizer_descquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizer',
            name='lenght',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizer',
            name='type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
