# Generated by Django 3.1.1 on 2020-11-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QUIZES', '0004_auto_20201115_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizer',
            name='length',
        ),
    ]
