# Generated by Django 3.1.1 on 2020-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LINKS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_link', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
